# Validate inputs for Quay team creation.

- name: Run - Quay - Team Create - Validate
  hosts: localhost
  gather_facts: false
  force_handlers: true

  tasks:
    - name: Check required arguments
      assert:
        that: "{{ param }} is defined and {{ param }} | length"
      loop:
        - survey_organization_name
        - survey_team_name
        - survey_team_role
      loop_control:
        loop_var: param

    - name: Validate team name format
      assert:
        that:
          - survey_team_name is match('^[a-z0-9][a-z0-9-]*[a-z0-9]$')
        fail_msg: "Team name '{{ survey_team_name }}' is invalid. Allowed characters: a-z, 0-9 and dash (-)"

    - name: Validate team role
      assert:
        that:
          - survey_team_role in ['member', 'creator', 'admin']
        fail_msg: "Team role '{{ survey_team_role }}' is invalid. Allowed values: member, creator, admin"

    - name: Display validation summary
      debug:
        msg: |
          Quay Team Create - Validation passed
          Organization: {{ survey_organization_name }}
          Team name:    {{ survey_team_name }}
          Team role:    {{ survey_team_role }}
          Description:  {{ survey_team_description | default('N/A') }}
