# Sync a Quay team with an LDAP group.

- name: Run - Quay - Team LDAP Sync
  hosts: localhost
  gather_facts: false
  force_handlers: true

  tasks:
    - name: Check required arguments
      assert:
        that: "{{ param }} is defined and {{ param }} | length"
      loop:
        - survey_organization_name
        - survey_team_name
        - survey_ldap_group_dn
      loop_control:
        loop_var: param

    - name: Generate pipeline definition
      set_fact:
        quay_pipeline:
          pipeline:
            - name: sync-team-ldap
              job: sync_team_ldap
              enabled: true
              params:
                organization: "{{ survey_organization_name }}"
                team_name: "{{ survey_team_name }}"
                group_dn: "{{ survey_ldap_group_dn }}"

    - name: Write pipeline file
      copy:
        content: "{{ quay_pipeline | to_nice_yaml(indent=2) }}"
        dest: "{{ fact_quay_pipeline_path }}"

    - name: Run quay-provisioner
      include_role:
        name: quay-provisioner-run
      vars:
        quay_pipeline_file: "{{ fact_quay_pipeline_path }}"
