# Validate inputs for Quay organization creation.
#
# Required arguments:
# - survey_organization_name: The organization name
# - survey_organization_email: Contact email
#

- name: Run - Quay - Organization Create - Validate
  hosts: localhost
  gather_facts: false
  force_handlers: true

  tasks:
    - name: Check required arguments
      assert:
        that: "{{ param }} is defined and {{ param }} | length"
      loop:
        - survey_organization_name
        - survey_organization_email
      loop_control:
        loop_var: param

    - name: Validate organization name format
      assert:
        that:
          - survey_organization_name is match('^[a-z0-9][a-z0-9-]*[a-z0-9]$')
        fail_msg: "Organization name '{{ survey_organization_name }}' is invalid. Allowed characters: a-z, 0-9 and dash (-). Must start and end with alphanumeric character."

    - name: Validate email format
      assert:
        that:
          - survey_organization_email is match('^[^@]+@[^@]+\.[^@]+$')
        fail_msg: "Email '{{ survey_organization_email }}' is not a valid email address."

    - name: Display validation summary
      debug:
        msg: |
          Quay Organization Create - Validation passed
          Organization: {{ survey_organization_name }}
          Email:        {{ survey_organization_email }}
          Create Robot: {{ survey_create_robot_account | default('false') }}
          Create Teams: {{ survey_create_default_teams | default('false') }}
