# Validate inputs for setting team repository permissions.

- name: Run - Quay - Team Repository Permission Set - Validate
  hosts: localhost
  gather_facts: false
  force_handlers: true

  tasks:
    - name: Check required arguments
      assert:
        that: "{{ param }} is defined and {{ param }} | length"
      loop:
        - survey_organization_name
        - survey_team_name
        - survey_repository_name
        - survey_permission_level
      loop_control:
        loop_var: param

    - name: Validate permission level
      assert:
        that:
          - survey_permission_level in ['read', 'write', 'admin']
        fail_msg: "Permission level '{{ survey_permission_level }}' is invalid. Allowed values: read, write, admin"

    - name: Display validation summary
      debug:
        msg: |
          Quay Team Repository Permission Set - Validation passed
          Organization: {{ survey_organization_name }}
          Team name:    {{ survey_team_name }}
          Repository:   {{ survey_repository_name }}
          Permission:   {{ survey_permission_level }}
