# Create a Quay organization with optional robot accounts and teams.
#
# Required arguments:
# - survey_organization_name: The organization name
# - survey_organization_email: Contact email
#
# Optional arguments:
# - survey_create_robot_account: Create a default ci-bot robot account (default: false)
# - survey_create_default_teams: Create default teams (default: false)
# - survey_permissions_groups_edit: LDAP groups with admin access
# - survey_permissions_groups_view: LDAP groups with read access
#

- name: Run - Quay - Organization Create
  hosts: localhost
  gather_facts: false
  force_handlers: true

  tasks:
    - name: Check required arguments
      assert:
        that: "{{ param }} is defined and {{ param }} | length"
      loop:
        - survey_organization_name
        - survey_organization_email
      loop_control:
        loop_var: param

    - name: Generate pipeline definition
      set_fact:
        quay_pipeline:
          pipeline:
            - name: create-organization
              job: create_organization
              enabled: true
              params:
                name: "{{ survey_organization_name }}"
                email: "{{ survey_organization_email }}"

    - name: Add robot account step
      set_fact:
        quay_pipeline: "{{ quay_pipeline | combine({'pipeline': quay_pipeline.pipeline + [robot_step]}, recursive=True) }}"
      vars:
        robot_step:
          name: create-robot-account
          job: create_robot_account
          enabled: true
          params:
            organization: "{{ survey_organization_name }}"
            robot_shortname: "ci-bot"
            description: "CI/CD automation bot"
      when:
        - survey_create_robot_account is defined
        - survey_create_robot_account | bool

    - name: Add default teams step (developers)
      set_fact:
        quay_pipeline: "{{ quay_pipeline | combine({'pipeline': quay_pipeline.pipeline + [team_step]}, recursive=True) }}"
      vars:
        team_step:
          name: create-team-developers
          job: create_team
          enabled: true
          params:
            organization: "{{ survey_organization_name }}"
            team_name: "developers"
            role: "creator"
            description: "Development team"
      when:
        - survey_create_default_teams is defined
        - survey_create_default_teams | bool

    - name: Add default teams step (viewers)
      set_fact:
        quay_pipeline: "{{ quay_pipeline | combine({'pipeline': quay_pipeline.pipeline + [team_step]}, recursive=True) }}"
      vars:
        team_step:
          name: create-team-viewers
          job: create_team
          enabled: true
          params:
            organization: "{{ survey_organization_name }}"
            team_name: "viewers"
            role: "member"
            description: "Read-only access team"
      when:
        - survey_create_default_teams is defined
        - survey_create_default_teams | bool

    - name: Add robot account to developers team
      set_fact:
        quay_pipeline: "{{ quay_pipeline | combine({'pipeline': quay_pipeline.pipeline + [member_step]}, recursive=True) }}"
      vars:
        member_step:
          name: add-robot-to-developers
          job: add_team_member
          enabled: true
          params:
            organization: "{{ survey_organization_name }}"
            team_name: "developers"
            member_name: "{{ survey_organization_name }}+ci-bot"
      when:
        - survey_create_robot_account is defined and survey_create_robot_account | bool
        - survey_create_default_teams is defined and survey_create_default_teams | bool

    - name: Add default repository permission for developers team
      set_fact:
        quay_pipeline: "{{ quay_pipeline | combine({'pipeline': quay_pipeline.pipeline + [perm_step]}, recursive=True) }}"
      vars:
        perm_step:
          name: set-default-repo-permission-developers
          job: set_default_repository_permission
          enabled: true
          params:
            organization: "{{ survey_organization_name }}"
            delegate:
              kind: "team"
              name: "developers"
            role: "admin"
      when:
        - survey_create_default_teams is defined
        - survey_create_default_teams | bool

    - name: Write pipeline file
      copy:
        content: "{{ quay_pipeline | to_nice_yaml(indent=2) }}"
        dest: "{{ fact_quay_pipeline_path }}"

    - name: Run quay-provisioner
      include_role:
        name: quay-provisioner-run
      vars:
        quay_pipeline_file: "{{ fact_quay_pipeline_path }}"

    - name: Display result
      debug:
        msg: |
          Quay Organization '{{ survey_organization_name }}' created successfully.
          Requester: {{ tower_user_name | default(lookup('env', 'USER')) }}
