# Validate inputs for setting default repository permissions.

- name: Run - Quay - Default Repository Permission Set - Validate
  hosts: localhost
  gather_facts: false
  force_handlers: true

  tasks:
    - name: Check required arguments
      assert:
        that: "{{ param }} is defined and {{ param }} | length"
      loop:
        - survey_quay_instance
        - survey_organization_name
        - survey_delegate_kind
        - survey_delegate_name
        - survey_permission_level
      loop_control:
        loop_var: param

    - name: Validate delegate kind
      assert:
        that:
          - survey_delegate_kind in ['team', 'user']
        fail_msg: "Delegate kind '{{ survey_delegate_kind }}' is invalid. Allowed values: team, user"

    - name: Validate permission level
      assert:
        that:
          - survey_permission_level in ['read', 'write', 'admin']
        fail_msg: "Permission level '{{ survey_permission_level }}' is invalid. Allowed values: read, write, admin"

    - name: Display validation summary
      debug:
        msg: |
          Quay Default Repository Permission Set - Validation passed
          Instance:     {{ survey_quay_instance }}
          Organization: {{ survey_organization_name }}
          Delegate:     {{ survey_delegate_kind }}/{{ survey_delegate_name }}
          Permission:   {{ survey_permission_level }}
