# Full Quay organization provisioning.
# Generates a Kubernetes ConfigMap with inputs.yaml from survey variables.
# The ConfigMap is used by the quay-provisioner Helm chart / ArgoCD.
#
# This creates in one workflow:
# - Organization
# - Robot Account(s)
# - Teams
# - Team Members (robot account added to teams)
# - Default Repository Permissions
# - LDAP Team Sync (optional)
#
# Required arguments:
# - survey_organization_name: Organization name
# - survey_organization_email: Contact email
# - survey_robot_shortname: Robot account name
# - survey_team_names: Comma-separated team names
# - survey_team_role: Default role for teams
#
# Optional arguments:
# - survey_ldap_group_dn: LDAP group DN for first team
#

- name: Run - Quay - Full Organization Provisioning
  hosts: localhost
  gather_facts: false
  force_handlers: true

  vars:
    quay_provisioner_namespace: quay-provisioner
    quay_provisioner_release_name: cluster
    quay_provisioner_configmap_name: "{{ quay_provisioner_release_name }}-quay-provisioner-inputs"

  tasks:
    - name: Check required arguments
      assert:
        that: "{{ param }} is defined and {{ param }} | length"
      loop:
        - survey_organization_name
        - survey_organization_email
        - survey_robot_shortname
        - survey_team_names
        - survey_team_role
      loop_control:
        loop_var: param

    - name: Parse team names
      set_fact:
        team_list: "{{ survey_team_names.split(',') | map('trim') | list }}"

    # -------------------------------------------------------------------------
    # Build inputs.yaml content from survey variables
    # -------------------------------------------------------------------------

    - name: Build organizations input
      set_fact:
        quay_inputs:
          organizations:
            - name: "{{ survey_organization_name }}"
              email: "{{ survey_organization_email }}"
              visibility: "{{ survey_organization_visibility }}"

    - name: Build robot accounts input
      set_fact:
        quay_inputs: "{{ quay_inputs | combine({'robot_accounts': [robot]}, recursive=True) }}"
      vars:
        robot:
          organization: "{{ survey_organization_name }}"
          robot_shortname: "{{ survey_robot_shortname }}"
          description: "CI automation bot"

    - name: Build teams input
      set_fact:
        quay_inputs: "{{ quay_inputs | combine({'teams': teams_list}, recursive=True) }}"
      vars:
        teams_list: >-
          [
          {% for team in team_list %}
            {
              "organization": "{{ survey_organization_name }}",
              "team_name": "{{ team }}",
              "role": "{{ survey_team_role }}",
              "description": "Team {{ team }}"
            }{% if not loop.last %},{% endif %}
          {% endfor %}
          ]

    - name: Build team members input (add robot to all teams)
      set_fact:
        quay_inputs: "{{ quay_inputs | combine({'team_members': members_list}, recursive=True) }}"
      vars:
        members_list: >-
          [
          {% for team in team_list %}
            {
              "organization": "{{ survey_organization_name }}",
              "team_name": "{{ team }}",
              "member_name": "{{ survey_organization_name }}+{{ survey_robot_shortname }}"
            }{% if not loop.last %},{% endif %}
          {% endfor %}
          ]

    - name: Build default repo permissions input
      set_fact:
        quay_inputs: "{{ quay_inputs | combine({'default_repo_permissions': perms_list}, recursive=True) }}"
      vars:
        perms_list: >-
          [
          {% for team in team_list %}
            {
              "organization": "{{ survey_organization_name }}",
              "delegate": {"kind": "team", "name": "{{ team }}"},
              "role": "admin"
            }{% if not loop.last %},{% endif %}
          {% endfor %}
          ]

    - name: Build LDAP sync input
      set_fact:
        quay_inputs: "{{ quay_inputs | combine({'team_ldap_sync': [ldap_entry]}, recursive=True) }}"
      vars:
        ldap_entry:
          organization: "{{ survey_organization_name }}"
          team_name: "{{ team_list | first }}"
          group_dn: "{{ survey_ldap_group_dn }}"
      when:
        - survey_ldap_group_dn is defined
        - survey_ldap_group_dn | length

    - name: Set empty LDAP sync input if not configured
      set_fact:
        quay_inputs: "{{ quay_inputs | combine({'team_ldap_sync': []}, recursive=True) }}"
      when:
        - survey_ldap_group_dn is not defined or survey_ldap_group_dn | length == 0

    # -------------------------------------------------------------------------
    # Generate and apply ConfigMap
    # -------------------------------------------------------------------------

    - name: Build ConfigMap
      set_fact:
        quay_configmap:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: "{{ quay_provisioner_configmap_name }}"
            namespace: "{{ quay_provisioner_namespace }}"
            labels:
              app.kubernetes.io/name: quay-provisioner
              app.kubernetes.io/instance: "{{ quay_provisioner_release_name }}"
              app.kubernetes.io/managed-by: Helm
          data:
            inputs.yaml: "{{ quay_inputs | to_nice_yaml(indent=2) }}"

    - name: Display generated ConfigMap
      debug:
        msg: "{{ quay_configmap | to_nice_yaml(indent=2) }}"

    - name: Apply ConfigMap to cluster
      k8s:
        state: present
        definition: "{{ quay_configmap }}"

    - name: Display result
      debug:
        msg: |
          Quay Organization '{{ survey_organization_name }}' - ConfigMap generated and applied.
          ConfigMap:     {{ quay_provisioner_configmap_name }}
          Namespace:     {{ quay_provisioner_namespace }}
          Robot account: {{ survey_organization_name }}+{{ survey_robot_shortname }}
          Teams:         {{ team_list | join(', ') }}
          LDAP Sync:     {{ survey_ldap_group_dn | default('not configured') }}
          Requester:     {{ tower_user_name | default(lookup('env', 'USER')) }}
