# Validate inputs for adding a member to a Quay team.

- name: Run - Quay - Team Member Add - Validate
  hosts: localhost
  gather_facts: false
  force_handlers: true

  tasks:
    - name: Check required arguments
      assert:
        that: "{{ param }} is defined and {{ param }} | length"
      loop:
        - survey_organization_name
        - survey_team_name
        - survey_member_name
      loop_control:
        loop_var: param

    - name: Display validation summary
      debug:
        msg: |
          Quay Team Member Add - Validation passed
          Organization: {{ survey_organization_name }}
          Team name:    {{ survey_team_name }}
          Member:       {{ survey_member_name }}
