# Provisions a complete Quay organization by generating a ConfigMap with the
# required inputs, committing it to the cluster-config Git repository, and
# triggering an ArgoCD sync.
#
# If an existing inputs ConfigMap file is found in the templates directory,
# the new organization data is merged into it. Otherwise a new file is created.
#
# This creates in one workflow:
# - Organization
# - Robot Account(s)
# - Teams
# - Team Members (robot account added to teams)
# - Default Repository Permissions
# - LDAP Team Sync (optional)
#
# Required arguments:
# - survey_organization_name: Organization name
# - survey_organization_email: Contact email
# - survey_organization_visibility: private or public
# - survey_robot_shortname: Robot account name
# - survey_team_names: Comma-separated team names
# - survey_team_role: Default role for teams
#
# Optional arguments:
# - survey_ldap_group_dn: LDAP group DN for first team
#
# Global variables (from vars file):
# - gitea_url: Gitea base URL
# - gitea_username: Gitea username
# - gitea_password: Gitea password
# - gitea_token: Gitea personal access token
#

- name: Run - Quay - Full Organization Provisioning
  hosts: localhost
  gather_facts: false
  force_handlers: true

  vars:
    # Git repository (gitea_url, gitea_username, gitea_password, gitea_token come from global vars)
    git_repo: "openshift/cluster-config"
    git_branch: main
    # Path inside the repo where the ConfigMap file will be created or updated
    templates_path: "helm/chartrepo/quay-provisioner/templates"
    # Name of the existing inputs ConfigMap file (if it exists, it will be extended)
    inputs_configmap_file: "inputs-config.yaml"
    # Fallback filename if no existing file is found
    generated_file_prefix: "auto-generated"

  tasks:
    - name: Check required arguments
      assert:
        that: "{{ param }} is defined and {{ param }} | length"
      loop:
        - survey_organization_name
        - survey_organization_email
        - survey_organization_visibility
        - survey_robot_shortname
        - survey_team_names
        - survey_team_role
      loop_control:
        loop_var: param

    - name: Parse team names
      set_fact:
        team_list: "{{ survey_team_names.split(',') | map('trim') | list }}"

    # -------------------------------------------------------------------------
    # Clone Git repository
    # -------------------------------------------------------------------------

    - name: Create temp directory for git clone
      tempfile:
        state: directory
        prefix: quay-provisioner-git-
      register: tmp_dir

    - name: Clone cluster-config repository
      git:
        repo: "{{ gitea_url | regex_replace('https://', 'https://' + gitea_token + '@') }}/{{ git_repo }}.git"
        dest: "{{ tmp_dir.path }}/cluster-config"
        version: "{{ git_branch }}"
        depth: 1

    - name: Set git path fact
      set_fact:
        fact_git_repo_path: "{{ tmp_dir.path }}/cluster-config"
        fact_templates_path: "{{ tmp_dir.path }}/cluster-config/{{ templates_path }}"

    - name: Configure git user
      command:
        cmd: "{{ item }}"
        chdir: "{{ fact_git_repo_path }}"
      loop:
        - git config user.name "{{ gitea_username }}"
        - git config user.email "{{ gitea_username }}@ansible-tower"

    # -------------------------------------------------------------------------
    # Check for existing inputs ConfigMap file
    # -------------------------------------------------------------------------

    - name: Check if inputs ConfigMap file exists
      stat:
        path: "{{ fact_templates_path }}/{{ inputs_configmap_file }}"
      register: existing_configmap_file

    - name: Read existing ConfigMap file
      slurp:
        src: "{{ fact_templates_path }}/{{ inputs_configmap_file }}"
      register: existing_configmap_raw
      when: existing_configmap_file.stat.exists

    - name: Parse existing inputs from ConfigMap
      set_fact:
        existing_configmap: "{{ existing_configmap_raw.content | b64decode | from_yaml }}"
        existing_inputs: "{{ (existing_configmap_raw.content | b64decode | from_yaml).data['inputs.yaml'] | from_yaml }}"
      when: existing_configmap_file.stat.exists

    - name: Initialize empty inputs if no existing file
      set_fact:
        existing_inputs:
          organizations: []
          robot_accounts: []
          teams: []
          team_members: []
          default_repo_permissions: []
          team_ldap_sync: []
      when: not existing_configmap_file.stat.exists

    # -------------------------------------------------------------------------
    # Build new entries from survey variables
    # -------------------------------------------------------------------------

    - name: Build organization entry
      set_fact:
        new_organization:
          name: "{{ survey_organization_name }}"
          email: "{{ survey_organization_email }}"
          visibility: "{{ survey_organization_visibility }}"

    - name: Build robot account entry
      set_fact:
        new_robot_account:
          organization: "{{ survey_organization_name }}"
          robot_shortname: "{{ survey_robot_shortname }}"
          description: "CI automation bot"

    - name: Build teams list
      set_fact:
        new_teams: >-
          [
          {% for team in team_list %}
            {
              "organization": "{{ survey_organization_name }}",
              "team_name": "{{ team }}",
              "role": "{{ survey_team_role }}",
              "description": "Team {{ team }}"
            }{% if not loop.last %},{% endif %}
          {% endfor %}
          ]

    - name: Build team members list (add robot to all teams)
      set_fact:
        new_team_members: >-
          [
          {% for team in team_list %}
            {
              "organization": "{{ survey_organization_name }}",
              "team_name": "{{ team }}",
              "member_name": "{{ survey_organization_name }}+{{ survey_robot_shortname }}"
            }{% if not loop.last %},{% endif %}
          {% endfor %}
          ]

    - name: Build default repo permissions list
      set_fact:
        new_default_repo_permissions: >-
          [
          {% for team in team_list %}
            {
              "organization": "{{ survey_organization_name }}",
              "delegate": {"kind": "team", "name": "{{ team }}"},
              "role": "admin"
            }{% if not loop.last %},{% endif %}
          {% endfor %}
          ]

    - name: Build LDAP sync entry
      set_fact:
        new_team_ldap_sync:
          - organization: "{{ survey_organization_name }}"
            team_name: "{{ team_list | first }}"
            group_dn: "{{ survey_ldap_group_dn }}"
      when:
        - survey_ldap_group_dn is defined
        - survey_ldap_group_dn | length

    - name: Set empty LDAP sync if not configured
      set_fact:
        new_team_ldap_sync: []
      when:
        - survey_ldap_group_dn is not defined or survey_ldap_group_dn | length == 0

    # -------------------------------------------------------------------------
    # Merge new entries into existing inputs
    # -------------------------------------------------------------------------

    - name: Remove existing entries for this organization (avoid duplicates)
      set_fact:
        cleaned_inputs:
          organizations: "{{ existing_inputs.organizations | default([]) | rejectattr('name', 'equalto', survey_organization_name) | list }}"
          robot_accounts: "{{ existing_inputs.robot_accounts | default([]) | rejectattr('organization', 'equalto', survey_organization_name) | list }}"
          teams: "{{ existing_inputs.teams | default([]) | rejectattr('organization', 'equalto', survey_organization_name) | list }}"
          team_members: "{{ existing_inputs.team_members | default([]) | rejectattr('organization', 'equalto', survey_organization_name) | list }}"
          default_repo_permissions: "{{ existing_inputs.default_repo_permissions | default([]) | rejectattr('organization', 'equalto', survey_organization_name) | list }}"
          team_ldap_sync: "{{ existing_inputs.team_ldap_sync | default([]) | rejectattr('organization', 'equalto', survey_organization_name) | list }}"

    - name: Merge new entries into inputs
      set_fact:
        merged_inputs:
          organizations: "{{ cleaned_inputs.organizations + [new_organization] }}"
          robot_accounts: "{{ cleaned_inputs.robot_accounts + [new_robot_account] }}"
          teams: "{{ cleaned_inputs.teams + new_teams }}"
          team_members: "{{ cleaned_inputs.team_members + new_team_members }}"
          default_repo_permissions: "{{ cleaned_inputs.default_repo_permissions + new_default_repo_permissions }}"
          team_ldap_sync: "{{ cleaned_inputs.team_ldap_sync + new_team_ldap_sync }}"

    # -------------------------------------------------------------------------
    # Write ConfigMap file
    # -------------------------------------------------------------------------

    - name: Set target filename
      set_fact:
        target_filename: "{{ inputs_configmap_file if existing_configmap_file.stat.exists else generated_file_prefix + '-inputs.yaml' }}"

    - name: Build ConfigMap content
      set_fact:
        fact_configmap_content:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: "{{ (existing_configmap.metadata.name) if existing_configmap_file.stat.exists else 'quay-provisioner-inputs' }}"
            labels:
              app.kubernetes.io/name: quay-provisioner
              app.kubernetes.io/managed-by: ansible-tower
              quay-provisioner/auto-generated: "true"
            annotations:
              quay-provisioner/last-modified-by: "{{ tower_user_name | default(lookup('env', 'USER')) }}"
              quay-provisioner/last-modified-at: "{{ now(utc=true).isoformat() }}"
          data:
            inputs.yaml: "{{ merged_inputs | to_nice_yaml(indent=2) }}"

    - name: Write ConfigMap to templates directory
      copy:
        content: "{{ fact_configmap_content | to_nice_yaml(indent=2) }}"
        dest: "{{ fact_templates_path }}/{{ target_filename }}"
      diff: yes

    - name: Display generated ConfigMap
      debug:
        msg: |
          Target file: {{ templates_path }}/{{ target_filename }}
          Mode: {{ 'UPDATED existing file' if existing_configmap_file.stat.exists else 'CREATED new file' }}
          {{ fact_configmap_content | to_nice_yaml(indent=2) }}

    # -------------------------------------------------------------------------
    # Commit and push to Gitea
    # -------------------------------------------------------------------------

    - name: Git add ConfigMap file
      command:
        cmd: git add "{{ templates_path }}/{{ target_filename }}"
        chdir: "{{ fact_git_repo_path }}"

    - name: Git commit
      command:
        cmd: >
          git commit -m "quay-provisioner: add organization {{ survey_organization_name }}

          Requester: {{ tower_user_name | default(lookup('env', 'USER')) }}
          Auto-generated by Ansible Tower"
        chdir: "{{ fact_git_repo_path }}"

    - name: Git push
      command:
        cmd: git push origin {{ git_branch }}
        chdir: "{{ fact_git_repo_path }}"

    # -------------------------------------------------------------------------
    # Cleanup
    # -------------------------------------------------------------------------

    - name: Cleanup temp directory
      file:
        path: "{{ tmp_dir.path }}"
        state: absent

    - name: Display result
      debug:
        msg: |
          Quay Organization '{{ survey_organization_name }}' - ConfigMap committed to Git.
          File:          {{ templates_path }}/{{ target_filename }}
          Mode:          {{ 'UPDATED existing file' if existing_configmap_file.stat.exists else 'CREATED new file' }}
          Visibility:    {{ survey_organization_visibility }}
          Robot account: {{ survey_organization_name }}+{{ survey_robot_shortname }}
          Teams:         {{ team_list | join(', ') }}
          LDAP Sync:     {{ survey_ldap_group_dn | default('not configured') }}
          Requester:     {{ tower_user_name | default(lookup('env', 'USER')) }}
