# Validate inputs for removing a Quay organization from the provisioning config.
#
# This workflow removes all entries for the organization from the ConfigMap
# (organization, robot accounts, teams, team members, default permissions,
# LDAP sync). The actual deletion of the organization in Quay must be done
# manually.
#
# Required arguments:
# - survey_organization_name: The organization name to remove from config
#

- name: Run - Quay - Full Organization Delete - Validate
  hosts: localhost
  gather_facts: false
  force_handlers: true

  tasks:
    - name: Check required arguments
      assert:
        that: "{{ param }} is defined and {{ param }} | length"
      loop:
        - survey_organization_name
      loop_control:
        loop_var: param

    - name: Display validation summary
      debug:
        msg: |
          WARNING: Quay Organization Config Removal
          Organization: {{ survey_organization_name }}
          This will remove ALL entries for this organization from the cluster-config ConfigMap:
          - Organization
          - Robot accounts
          - Teams
          - Team members
          - Default repository permissions
          - LDAP sync settings
          ArgoCD will no longer manage this organization after the next sync.
          NOTE: The organization in Quay itself must be deleted manually!
          Requester: {{ tower_user_name | default(lookup('env', 'USER')) }}
