# Full Quay organization provisioning.
# Generates inputs.yaml content from survey variables and commits it to the
# self-service Git repository. ArgoCD picks up the change and the Helm chart
# generates the ConfigMap for the quay-provisioner.
#
# This creates in one workflow:
# - Organization
# - Robot Account(s)
# - Teams
# - Team Members (robot account added to teams)
# - Default Repository Permissions
# - LDAP Team Sync (optional)
#
# Required arguments:
# - survey_organization_name: Organization name
# - survey_organization_email: Contact email
# - survey_organization_visibility: private or public
# - survey_robot_shortname: Robot account name
# - survey_team_names: Comma-separated team names
# - survey_team_role: Default role for teams
#
# Optional arguments:
# - survey_ldap_group_dn: LDAP group DN for first team
#

- name: Run - Quay - Full Organization Provisioning
  hosts: localhost
  gather_facts: false
  force_handlers: true

  tasks:
    - name: Check required arguments
      assert:
        that: "{{ param }} is defined and {{ param }} | length"
      loop:
        - survey_organization_name
        - survey_organization_email
        - survey_organization_visibility
        - survey_robot_shortname
        - survey_team_names
        - survey_team_role
      loop_control:
        loop_var: param

    - name: Parse team names
      set_fact:
        team_list: "{{ survey_team_names.split(',') | map('trim') | list }}"

    # -------------------------------------------------------------------------
    # Clone Git repository
    # -------------------------------------------------------------------------

    - name: Clone self-service repository
      include_role:
        name: quay-provisioner-git

    # -------------------------------------------------------------------------
    # Read existing values
    # -------------------------------------------------------------------------

    - name: Read existing values
      include_role:
        name: quay-provisioner-values
      vars:
        quay_values_git_path: "{{ fact_quay_git_path }}"
        quay_values_organization_name: "{{ survey_organization_name }}"

    # -------------------------------------------------------------------------
    # Build inputs from survey variables
    # -------------------------------------------------------------------------

    - name: Build organization entry
      set_fact:
        fact_organization:
          name: "{{ survey_organization_name }}"
          email: "{{ survey_organization_email }}"
          visibility: "{{ survey_organization_visibility }}"

    - name: Build robot account entry
      set_fact:
        fact_robot_account:
          organization: "{{ survey_organization_name }}"
          robot_shortname: "{{ survey_robot_shortname }}"
          description: "CI automation bot"

    - name: Build teams list
      set_fact:
        fact_teams: >-
          [
          {% for team in team_list %}
            {
              "organization": "{{ survey_organization_name }}",
              "team_name": "{{ team }}",
              "role": "{{ survey_team_role }}",
              "description": "Team {{ team }}"
            }{% if not loop.last %},{% endif %}
          {% endfor %}
          ]

    - name: Build team members list (add robot to all teams)
      set_fact:
        fact_team_members: >-
          [
          {% for team in team_list %}
            {
              "organization": "{{ survey_organization_name }}",
              "team_name": "{{ team }}",
              "member_name": "{{ survey_organization_name }}+{{ survey_robot_shortname }}"
            }{% if not loop.last %},{% endif %}
          {% endfor %}
          ]

    - name: Build default repo permissions list
      set_fact:
        fact_default_repo_permissions: >-
          [
          {% for team in team_list %}
            {
              "organization": "{{ survey_organization_name }}",
              "delegate": {"kind": "team", "name": "{{ team }}"},
              "role": "admin"
            }{% if not loop.last %},{% endif %}
          {% endfor %}
          ]

    - name: Build LDAP sync entry
      set_fact:
        fact_team_ldap_sync:
          - organization: "{{ survey_organization_name }}"
            team_name: "{{ team_list | first }}"
            group_dn: "{{ survey_ldap_group_dn }}"
      when:
        - survey_ldap_group_dn is defined
        - survey_ldap_group_dn | length

    - name: Set empty LDAP sync if not configured
      set_fact:
        fact_team_ldap_sync: []
      when:
        - survey_ldap_group_dn is not defined or survey_ldap_group_dn | length == 0

    # -------------------------------------------------------------------------
    # Update values dict
    # -------------------------------------------------------------------------

    - name: Update values dict
      set_fact:
        fact_quay_values_dict: "{{ fact_quay_values_dict | default({}) | combine(values, recursive=True) }}"
      vars:
        values:
          organizations:
            - "{{ fact_organization }}"
          robot_accounts:
            - "{{ fact_robot_account }}"
          teams: "{{ fact_teams }}"
          team_members: "{{ fact_team_members }}"
          default_repo_permissions: "{{ fact_default_repo_permissions }}"
          team_ldap_sync: "{{ fact_team_ldap_sync }}"

    # -------------------------------------------------------------------------
    # Write values and commit to Git
    # -------------------------------------------------------------------------

    - name: Write updated values
      include_role:
        name: quay-provisioner-values
      vars:
        quay_values_dict: "{{ fact_quay_values_dict }}"
        quay_values_git_path: "{{ fact_quay_git_path }}"
        quay_values_organization_name: "{{ survey_organization_name }}"

    - name: Commit and push changes
      include_role:
        name: quay-provisioner-git
      vars:
        quay_git_path: "{{ fact_quay_git_path }}"

    # -------------------------------------------------------------------------
    # Trigger ArgoCD sync
    # -------------------------------------------------------------------------

    - name: Trigger ArgoCD sync
      include_role:
        name: quay-provisioner-argocd

    - name: Display result
      debug:
        msg: |
          Quay Organization '{{ survey_organization_name }}' fully provisioned.
          Visibility:    {{ survey_organization_visibility }}
          Robot account: {{ survey_organization_name }}+{{ survey_robot_shortname }}
          Teams:         {{ team_list | join(', ') }}
          LDAP Sync:     {{ survey_ldap_group_dn | default('not configured') }}
          Requester:     {{ tower_user_name | default(lookup('env', 'USER')) }}
