# Full Quay organization provisioning.
# Clones the cluster-config Gitea repository, generates a ConfigMap YAML file
# with the inputs.yaml in the Helm templates directory, commits and pushes.
# ArgoCD picks up the change and the quay-provisioner Job runs.
#
# This creates in one workflow:
# - Organization
# - Robot Account(s)
# - Teams
# - Team Members (robot account added to teams)
# - Default Repository Permissions
# - LDAP Team Sync (optional)
#
# Required arguments:
# - survey_organization_name: Organization name
# - survey_organization_email: Contact email
# - survey_organization_visibility: private or public
# - survey_robot_shortname: Robot account name
# - survey_team_names: Comma-separated team names
# - survey_team_role: Default role for teams
#
# Optional arguments:
# - survey_ldap_group_dn: LDAP group DN for first team
#

- name: Run - Quay - Full Organization Provisioning
  hosts: localhost
  gather_facts: false
  force_handlers: true

  vars:
    # Git repository (gitea_url, gitea_username, gitea_password, gitea_token come from global vars)
    git_repo: "openshift/cluster-config"
    git_repo_url: "{{ gitea_url }}/{{ git_repo }}.git"
    git_branch: main
    # Path inside the repo where the ConfigMap file will be created
    templates_path: "helm/chartrepo/quay-provisioner/templates"
    # Generated file prefix (result: auto-generated-<org-name>-inputs.yaml)
    generated_file_prefix: "auto-generated"

  tasks:
    - name: Check required arguments
      assert:
        that: "{{ param }} is defined and {{ param }} | length"
      loop:
        - survey_organization_name
        - survey_organization_email
        - survey_organization_visibility
        - survey_robot_shortname
        - survey_team_names
        - survey_team_role
      loop_control:
        loop_var: param

    - name: Parse team names
      set_fact:
        team_list: "{{ survey_team_names.split(',') | map('trim') | list }}"

    - name: Set generated filename
      set_fact:
        generated_filename: "{{ generated_file_prefix }}-{{ survey_organization_name }}-inputs.yaml"

    # -------------------------------------------------------------------------
    # Clone Git repository
    # -------------------------------------------------------------------------

    - name: Create temp directory for git clone
      tempfile:
        state: directory
        prefix: quay-provisioner-git-
      register: tmp_dir

    - name: Clone cluster-config repository
      git:
        repo: "{{ gitea_url | regex_replace('https://', 'https://' + gitea_token + '@') }}/{{ git_repo }}.git"
        dest: "{{ tmp_dir.path }}/cluster-config"
        version: "{{ git_branch }}"
        depth: 1

    - name: Set git path fact
      set_fact:
        fact_git_repo_path: "{{ tmp_dir.path }}/cluster-config"
        fact_templates_path: "{{ tmp_dir.path }}/cluster-config/{{ templates_path }}"

    - name: Configure git user
      command:
        cmd: "{{ item }}"
        chdir: "{{ fact_git_repo_path }}"
      loop:
        - git config user.name "{{ gitea_username }}"
        - git config user.email "{{ gitea_username }}@ansible-tower"

    # -------------------------------------------------------------------------
    # Build inputs.yaml content from survey variables
    # -------------------------------------------------------------------------

    - name: Build organization entry
      set_fact:
        fact_organization:
          name: "{{ survey_organization_name }}"
          email: "{{ survey_organization_email }}"
          visibility: "{{ survey_organization_visibility }}"

    - name: Build robot account entry
      set_fact:
        fact_robot_account:
          organization: "{{ survey_organization_name }}"
          robot_shortname: "{{ survey_robot_shortname }}"
          description: "CI automation bot"

    - name: Build teams list
      set_fact:
        fact_teams: >-
          [
          {% for team in team_list %}
            {
              "organization": "{{ survey_organization_name }}",
              "team_name": "{{ team }}",
              "role": "{{ survey_team_role }}",
              "description": "Team {{ team }}"
            }{% if not loop.last %},{% endif %}
          {% endfor %}
          ]

    - name: Build team members list (add robot to all teams)
      set_fact:
        fact_team_members: >-
          [
          {% for team in team_list %}
            {
              "organization": "{{ survey_organization_name }}",
              "team_name": "{{ team }}",
              "member_name": "{{ survey_organization_name }}+{{ survey_robot_shortname }}"
            }{% if not loop.last %},{% endif %}
          {% endfor %}
          ]

    - name: Build default repo permissions list
      set_fact:
        fact_default_repo_permissions: >-
          [
          {% for team in team_list %}
            {
              "organization": "{{ survey_organization_name }}",
              "delegate": {"kind": "team", "name": "{{ team }}"},
              "role": "admin"
            }{% if not loop.last %},{% endif %}
          {% endfor %}
          ]

    - name: Build LDAP sync entry
      set_fact:
        fact_team_ldap_sync:
          - organization: "{{ survey_organization_name }}"
            team_name: "{{ team_list | first }}"
            group_dn: "{{ survey_ldap_group_dn }}"
      when:
        - survey_ldap_group_dn is defined
        - survey_ldap_group_dn | length

    - name: Set empty LDAP sync if not configured
      set_fact:
        fact_team_ldap_sync: []
      when:
        - survey_ldap_group_dn is not defined or survey_ldap_group_dn | length == 0

    # -------------------------------------------------------------------------
    # Assemble inputs dict
    # -------------------------------------------------------------------------

    - name: Assemble inputs
      set_fact:
        fact_quay_inputs:
          organizations:
            - "{{ fact_organization }}"
          robot_accounts:
            - "{{ fact_robot_account }}"
          teams: "{{ fact_teams }}"
          team_members: "{{ fact_team_members }}"
          default_repo_permissions: "{{ fact_default_repo_permissions }}"
          team_ldap_sync: "{{ fact_team_ldap_sync }}"

    # -------------------------------------------------------------------------
    # Generate ConfigMap YAML and write to templates directory
    # -------------------------------------------------------------------------

    - name: Build ConfigMap content
      set_fact:
        fact_configmap_content:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: "quay-provisioner-{{ survey_organization_name }}-inputs"
            labels:
              app.kubernetes.io/name: quay-provisioner
              app.kubernetes.io/managed-by: ansible-tower
              quay-provisioner/auto-generated: "true"
              quay-provisioner/organization: "{{ survey_organization_name }}"
            annotations:
              quay-provisioner/generated-by: "{{ tower_user_name | default(lookup('env', 'USER')) }}"
              quay-provisioner/generated-at: "{{ now(utc=true).isoformat() }}"
          data:
            inputs.yaml: "{{ fact_quay_inputs | to_nice_yaml(indent=2) }}"

    - name: Write ConfigMap to templates directory
      copy:
        content: "{{ fact_configmap_content | to_nice_yaml(indent=2) }}"
        dest: "{{ fact_templates_path }}/{{ generated_filename }}"
      diff: yes

    - name: Display generated ConfigMap
      debug:
        msg: |
          Generated file: {{ templates_path }}/{{ generated_filename }}
          {{ fact_configmap_content | to_nice_yaml(indent=2) }}

    # -------------------------------------------------------------------------
    # Commit and push to Gitea
    # -------------------------------------------------------------------------

    - name: Git add generated file
      command:
        cmd: git add "{{ templates_path }}/{{ generated_filename }}"
        chdir: "{{ fact_git_repo_path }}"

    - name: Git commit
      command:
        cmd: >
          git commit -m "quay-provisioner: add organization {{ survey_organization_name }}

          Requester: {{ tower_user_name | default(lookup('env', 'USER')) }}
          Auto-generated by Ansible Tower"
        chdir: "{{ fact_git_repo_path }}"

    - name: Git push
      command:
        cmd: git push origin {{ git_branch }}
        chdir: "{{ fact_git_repo_path }}"

    # -------------------------------------------------------------------------
    # Cleanup
    # -------------------------------------------------------------------------

    - name: Cleanup temp directory
      file:
        path: "{{ tmp_dir.path }}"
        state: absent

    - name: Display result
      debug:
        msg: |
          Quay Organization '{{ survey_organization_name }}' - ConfigMap committed to Git.
          File:          {{ templates_path }}/{{ generated_filename }}
          Visibility:    {{ survey_organization_visibility }}
          Robot account: {{ survey_organization_name }}+{{ survey_robot_shortname }}
          Teams:         {{ team_list | join(', ') }}
          LDAP Sync:     {{ survey_ldap_group_dn | default('not configured') }}
          Requester:     {{ tower_user_name | default(lookup('env', 'USER')) }}
