# Validate inputs for removing team repository permissions.

- name: Run - Quay - Team Repository Permission Remove - Validate
  hosts: localhost
  gather_facts: false
  force_handlers: true

  tasks:
    - name: Check required arguments
      assert:
        that: "{{ param }} is defined and {{ param }} | length"
      loop:
        - survey_quay_instance
        - survey_organization_name
        - survey_team_name
        - survey_repository_name
      loop_control:
        loop_var: param

    - name: Display validation summary
      debug:
        msg: |
          Quay Team Repository Permission Remove - Validation passed
          Instance:     {{ survey_quay_instance }}
          Organization: {{ survey_organization_name }}
          Team name:    {{ survey_team_name }}
          Repository:   {{ survey_repository_name }}
