input_file: "pipelines/inputs.yaml"

pipeline:
  - name: create-organizations
    job: create_organization
    enabled: false
    params_list: "{{ inputs.organizations }}"

  - name: create-robot-accounts
    job: create_robot_account
    enabled: true
    params_list: "{{ inputs.robot_accounts }}"