pipeline:
  - name: create-organizations
    job: create_organization
    enabled: true
    params_list: "{{ organizations }}"

  - name: create-robot-accounts
    job: create_robot_account
    enabled: true
    params_list: "{{ robot_accounts }}"

  - name: create-teams
    job: create_team
    enabled: true
    params_list: "{{ teams }}"

  - name: add-team-members
    job: add_team_member
    enabled: true
    params_list: "{{ team_members }}"

  - name: sync-teams-ldap
    job: sync_team_ldap
    enabled: false
    params_list: "{{ team_ldap_sync }}"

  - name: remove-team-members
    job: remove_team_member
    enabled: false
    params_list: "{{ team_members_to_remove }}"

  - name: disable-team-ldap-sync
    job: unsync_team_ldap
    enabled: false
    params_list: "{{ team_ldap_unsync }}"

  - name: get-team-ldap-sync-status
    job: get_team_sync_status
    enabled: false
    params_list: "{{ team_sync_status }}"
